import {GoogleGenAI} from "@google/genai"
import {z} from "zod"
import {zodToJsonSchema} from "zod-to-json-schema"
import puppeteer from "puppeteer"


const ai = new GoogleGenAI({
    apiKey : process.env.GOOGLE_GENAI_API_KEY
})

const interviewReportSchema = z.object({
    matchScore: z.number().describe("A score between 0 and 100 indicating how well the candidate's profile matches the job describe"),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical question can be asked in the interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take etc.")
    })).describe("Technical questions that can be asked in the interview along with their intention and how to answer them"),
    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The technical questions that can be asked in the interview"),
        intention: z.string().describe("The intention of interviewer behind asking this question"),
        answer: z.string().describe("How to answer this question, what points to cover, what approach to take etc.")
    })).describe("Behavioral questions that can be asked in the interview along with their intention and how to answer them"),
    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill which the candidate is lacking"),
        severity: z.enum([ "low", "medium", "high" ]).describe("The severity of this skill gap, i.e. how important is this skill for the job and how much it can impact the candidate's chances")
    })).describe("List of skill gaps in the candidate's profile along with their severity"),
    preparationPlan: z.array(z.object({
        day: z.number().describe("The day number in the preparation plan, starting from 1"),
        focus: z.string().describe("The main focus of this day in the preparation plan, e.g. data structures, system design, mock interviews etc."),
        tasks: z.array(z.string()).describe("List of tasks to be done on this day to follow the preparation plan, e.g. read a specific book or article, solve a set of problems, watch a video etc.")
    })).describe("A day-wise preparation plan for the candidate to follow in order to prepare for the interview effectively"),
    title: z.string().describe("The title of the job for which the interview report is generated"),
})




export async function generateInterviewReport({ resume, selfDescription, jobDescription }) {


    const prompt = `Generate an interview report for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}
                    IMPORTANT:
- Return ONLY valid JSON.
- Include ALL fields specified in the schema.
- The "title" field MUST contain the job title extracted from the job description (for example: "MERN Stack Developer", "Frontend Engineer", etc.)
- MUST generate the technical questions , behaviral questions and skill gap as per schema
`

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(interviewReportSchema),
        }
    })

    return JSON.parse(response.text)


}

export async function generateResumePdf({
    resume,
    selfDescription,
    jobDescription
}) {
    try {
        const resumePdfSchema = z.object({
            html: z
                .string()
                .describe(
                    "The HTML content of the resume which can be converted to PDF using any library like puppeteer"
                )
        });

        const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        The response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience.
                        The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        You can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly.
                        The resume should ideally be 1–2 pages long when converted to PDF.
                    `;

        let response;

        try {
            response = await ai.models.generateContent({
                model: "gemini-3-flash-preview",
                contents: prompt,
                config: {
                    responseMimeType: "application/json",
                    responseSchema: zodToJsonSchema(resumePdfSchema),
                },
            });
        } catch (error) {
            console.error("Gemini API error:", error);

            throw new Error(
                "Failed to generate resume content using AI."
            );
        }

        let parsedContent;

        try {
            parsedContent = JSON.parse(response.text);
        } catch (error) {
            console.error("Invalid JSON returned by Gemini:", response.text);

            throw new Error(
                "AI returned an invalid response format."
            );
        }

        const validationResult =
            resumePdfSchema.safeParse(parsedContent);

        if (!validationResult.success) {
            console.error(
                "Schema validation failed:",
                validationResult.error
            );

            throw new Error(
                "Generated resume content failed validation."
            );
        }

        try {
            const pdfBuffer = await generatePdfFromHtml(
                validationResult.data.html
            );

            return pdfBuffer;
        } catch (error) {
            console.error("PDF generation failed:", error);

            throw new Error(
                "Failed to generate PDF from resume HTML."
            );
        }
    } catch (error) {
        console.error("generateResumePdf error:", error);

        throw error;
    }
}

export async function generatePdfFromHtml(htmlContent) {
    let browser;

    try {
        browser = await puppeteer.launch();

        const page = await browser.newPage();

        await page.setContent(htmlContent, {
            waitUntil: "networkidle0",
            timeout: 30000, // 30 seconds
        });

        const pdfBuffer = await page.pdf({
            format: "A4",
            margin: {
                top: "20mm",
                bottom: "20mm",
                left: "15mm",
                right: "15mm",
            },
        });

        return pdfBuffer;
    } catch (error) {
        console.error("PDF generation error:", error);

        throw new Error(
            error instanceof Error
                ? `Failed to generate PDF: ${error.message}`
                : "Failed to generate PDF."
        );
    } finally {
        if (browser) {
            try {
                await browser.close();
            } catch (closeError) {
                console.error(
                    "Failed to close browser:",
                    closeError
                );
            }
        }
    }
}

